pipeline:
  identifier: Build_cortex_plugin_infraweave_1754670234927
  name: Build cortex-plugin-infraweave
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: ms_gh
        repoName: cortex-plugin-infraweave
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: |-
                      echo -n "id: "
                      id
                      echo -n "pwd: "
                      pwd
                      echo "home: ${HOME}"
                      . "$HOME/.nvm/nvm.sh"
                      nvm install v22
                      export COREPACK_ENABLE_DOWNLOAD_PROMPT=0 && corepack enable yarn
                      yarn
                      yarn build
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
